# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
#this is a 1d array. if I want a matrix or 2d, I can do a list of lists
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr = np.array(my_mat)

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#there are faster ways to make numpy arrasy

In [15]:
np.arange(0,10) #up to but not including

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2) #step size

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(3) #if we want this??

array([0., 0., 0.])

In [21]:
np.zeros((2,5)) #if we want a height and width of zeros?

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((3,4)) #simlar

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# LENSE SPACE evenly spaced numbers over interval?

np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
#identity matrix
#square. diagnal of 1s

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#arrays of random numbers

np.random.rand(5) #if you awand 1d uniform numbers

array([0.15210003, 0.26123189, 0.64030597, 0.33422418, 0.15615179])

In [29]:
np.random.rand(5,5) #if you want 2d aray

array([[0.4674943 , 0.04151786, 0.70833461, 0.61360155, 0.05887034],
       [0.69214455, 0.45765444, 0.38836816, 0.14940112, 0.52941391],
       [0.20038586, 0.21359936, 0.95204872, 0.65008777, 0.95658188],
       [0.08925121, 0.98932658, 0.8198138 , 0.44749922, 0.37044561],
       [0.3979967 , 0.01959721, 0.81402108, 0.42789498, 0.23464004]])

In [30]:
np.random.randn(2) #numbers not from uniform distribution but on a distribution based on zero

array([-0.44675463, -0.88003698])

In [32]:
np.random.randn(2,2) #or 2d

array([[-1.12806655, -0.29873473],
       [ 1.33017489, -0.56998202]])

In [34]:
np.random.randint(1,100) #a random int between 1 and 100

35

In [36]:
np.random.randint(1,100, 10) #10 random int

array([59, 70, 80, 29, 83, 47, 47, 44, 72,  3])

### But why are arrays useful?

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
ranarr

array([ 2,  7, 35,  7, 43, 22,  3, 44, 35, 21])

In [41]:
#reshape methods. Same data with a new shape...

In [43]:
arr.reshape(5,5) #now we see it in a 5*5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr

array([ 2,  7, 35,  7, 43, 22,  3, 44, 35, 21])

In [45]:
ranarr.max()

44

In [46]:
ranarr.min()

2

In [47]:
ranarr

array([ 2,  7, 35,  7, 43, 22,  3, 44, 35, 21])

In [48]:
#location of max/min

In [50]:
ranarr.argmax() #max at index location 7!

7

In [51]:
ranarr.argmin() #min is at index location 0

0

In [52]:
arr.shape #it is 25 in a line

(25,)

In [53]:
arr = arr.reshape(5,5)

In [54]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
arr.shape #now it is a 5*5

(5, 5)

In [58]:
arr.dtype #it is  a32 bit int

dtype('int32')

In [59]:
from numpy.random import randint

In [60]:
randint(2,10)

2