In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0]

0

In [5]:
arr[9]

9

In [6]:
#if I want to get values in a range

arr[1:5]

array([1, 2, 3, 4])

In [7]:
 arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[-1:]

array([10])

In [11]:
arr[]

array([], dtype=int32)

### broadcast!

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_off_arr = arr[0:6]

In [18]:
slice_off_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_off_arr[:] = 99

In [20]:
slice_off_arr

array([99, 99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
#changes on slice and on org

In [23]:
#if you want a copy and not a ref of original...

In [24]:
arr_copy = arr.copy()

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr_copy[:] = 100

In [31]:
arr_copy #now we changed the copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [32]:
arr #but our arr original is the same

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### indexing a 2d array (matrix)

In [35]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [36]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
#double bracket format.

In [40]:
arr_2d[0] #this will return row

array([ 5, 10, 15])

In [41]:
arr_2d[0][0] #this will return quardinates

5

In [42]:
arr_2d[2][1]

40

In [44]:
#suggested way (but same thing)
arr_2d[2,1]

40

In [46]:
arr_2d[:2,1:] #grabing chuncks rows up to not including 2. Colums 1 to end

array([[10, 15],
       [25, 30]])

In [47]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [52]:
arr_2d[0:,0]

array([ 5, 20, 35])

### conditional selection

In [53]:
arr = np.arange(1,11)

In [54]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr >5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [56]:
bool_arr = arr >5

In [57]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [59]:
#this is cool!
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [62]:
bool_arr2 = arr <3

In [63]:
arr[bool_arr2]

array([1, 2])

In [65]:
#or simplified

arr[arr<3]

array([1, 2])

In [66]:
arr_2d = np.arange(50).reshape(5,10)

In [67]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [70]:
arr_2d[3:,8:]

array([[38, 39],
       [48, 49]])

In [71]:
arr_2d[1,1:6]

array([11, 12, 13, 14, 15])