# Operations

In [1]:
### Array with Array

In [2]:
### Array with Scalars

In [3]:
### Universal Array Func

In [4]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr* arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
#scalar operations. Single number broadcast element to element

In [13]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [14]:
arr * 55

array([  0,  55, 110, 165, 220, 275, 330, 385, 440, 495, 550])

In [15]:
arr - 9

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1])

In [16]:
arr /2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [17]:
#soemtime will outup warning rather than an error.

In [19]:
1/0 #actual error

ZeroDivisionError: division by zero

In [21]:
arr / arr #here [0] is  0 can't 0/0 but it moves on and does the rest

C:\Users\dansc\AppData\Local\Temp\ipykernel_15728\1460198621.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr #here [0] is  0 can't 0/0 but it moves on and does the rest


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [22]:
#can also see something called inf that is caused by similar

In [23]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### universal array functions

In [25]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [26]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [27]:
np.max(arr)

10

In [29]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [30]:
np.log(arr)

C:\Users\dansc\AppData\Local\Temp\ipykernel_15728\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])